/*
 * webapi RowData
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webapi

import (
	"errors"
)

// RowdataApiService is a service that implents the logic for the RowdataApiServicer
// This service should implement the business logic for every endpoint for the RowdataApi API. 
// Include any external packages or services that will be required by this service.
type RowdataApiService struct {
}

// NewRowdataApiService creates a default api service
func NewRowdataApiService() RowdataApiServicer {
	return &RowdataApiService{}
}

// GetRowData - get rowdata information
func (s *RowdataApiService) GetRowData(title string) (interface{}, error) {
	// TODO - update GetRowData with the required logic for this service method.
	// Add api_rowdata_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetRowData' not implemented")
}
