/*
 * webapi RowData
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webapi

type RowData struct {

	Title string `json:"title"`

	Detail string `json:"detail"`
}
