/*
 * webapi RowData
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	webapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	RowdataApiService := webapi.NewRowdataApiService()
	RowdataApiController := webapi.NewRowdataApiController(RowdataApiService)

	router := webapi.NewRouter(RowdataApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
